### ISSUE TITLE
Ambigious README with regards to copyright

### ISSUE THREAD

**Issue by Wuzzy2** [Soldat/base#13]
I'm very sorry to bother you again about copyright, and it's actually more like a nitpick: Here's a friendly note that the current README is a little ambigious:

> CC BY 4.0
> 
> Soldat and all the file formats the program produces are Copyright © 2001-2018 Michal Marcinkowski. All rights reserved.

You can't be CC BY and “All rights reserved” at the same time. While I believe the phrase “All rights reserved” has no legal meaning, it can be very confusing to most. With CC BY you give up some of the rights of copyright, but “All rights reserved” (usually) means you give no of the rights, which, of course, is incompatible with Creative Commons. I'm sure you meant the CC BY, but for outsiders it might be not so obvious. https://en.wikipedia.org/wiki/All_rights_reserved

Since you intended to use CC BY, I suggest to remove the phrase “All rights reserved” from the README to resolve the confusion.

**Comment by BranDougherty** [comment]
I looked into this, and I agree with your assessment that MM would lose no rights if we remove that notice. I think it was just left over from before we decided on CC BY 4.0.

Done in dbd78ebf3681b6309495b6fcaa23f1c7ad1076b1.
