### ISSUE TITLE
3 missing files in interface-gfx folder

### ISSUE THREAD

**Issue by SwamiUmami** [Soldat/base#20]
When running client with `log_level` cvar set to 1, you can see that it fails to load 3 files from `interface-gfx` folder:
```
[PhysFS] Loading file interface-gfx/friend.bmp
[GFX] Failed to load image interface-gfx/friend.bmp
[PhysFS] Loading file interface-gfx/mic.bmp
[GFX] Failed to load image interface-gfx/mic.bmp
[PhysFS] Loading file interface-gfx/connection.bmp
[GFX] Failed to load image interface-gfx/connection.bmp
```

We need 3 files (despite the `.bmp` extension in logs, client can also load from `.png`):
- [x] `friend.png`
- [x] `mic.png`
- [x] `connection.png`

`friend.png` and `mic.png` are only used in Steam builds. `connection.png` is displayed in F1 menu, and I think it's meant to show connection quality.

**Comment by BranDougherty** [comment]
Not a graphic designer, but I made some icons for these. If anyone wants to do them better, they are just 50x50, vertically and horizontally centered pngs. I just threw it into #21 but if that stagnates I'll make this its own PR.

![shot_04-2022-25_21-08-29](https://user-images.githubusercontent.com/19610490/165207497-657cf489-e265-4587-837e-2c2911422581.png)
